/*
	This file is part of solidity.

	solidity is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	solidity is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with solidity.  If not, see <http://www.gnu.org/licenses/>.
*/
// SPDX-License-Identifier: GPL-3.0

#pragma once

#include <libevmasm/Assembly.h>

#include <libsolidity/interface/CompilerStack.h>

#include <libsolutil/Common.h>

using namespace solidity;
using namespace solidity::util;

namespace solidity::frontend::test
{

struct AnnotatedEventSignature
{
	std::string signature;
	std::vector<std::string> indexedTypes;
	std::vector<std::string> nonIndexedTypes;
};

enum class MetadataFormat {
	WithReleaseVersionTag,
	WithPrereleaseVersionTag,
	NoMetadata
};

enum class MetadataHash {
	IPFS,
	Bzzr1,
	None
};

struct CompilerInput
{
	CompilerInput() = default;

	/// Source code to be compiled
	std::map<std::string, std::string> sourceCode;
	/// Information on which library is deployed where
	std::map<std::string, solidity::util::h160> libraryAddresses;
	/// Contract name without a colon prefix
	std::optional<std::string> contractName;
	/// EVM target version
	std::optional<langutil::EVMVersion> evmVersion;
	/// EOF version
	std::optional<uint8_t> eofVersion;
	/// If optimisation should be enabled.
	std::optional<bool> optimise;
	/// Optimiser setting to be used during compilation
	std::optional<frontend::OptimiserSettings> optimiserSettings;
	/// Revert string behaviour
	std::optional<RevertStrings> revertStrings;
	/// Format of the metadata appended at the end of the bytecode
	std::optional<MetadataFormat> metadataFormat;
	/// Hash should be used to store the metadata in the bytecode
	std::optional<MetadataHash> metadataHash;
	/// Flag used for debugging
	std::optional<bool> debugFailure;
	/// Flag to enable new code generator
	std::optional<bool> viaIR;
};

/**
 * A compiled contract.
 */
struct CompiledContract
{
	/// The name of the contract
	std::string name;
	/// Bytecode of the assembled object for a contract.
	bytes object;
	/// Bytecode of the assembled runtime object for a contract.
	bytes runtimeObject;
	/// If object has unlinked references.
	bool hasUnlinkedReferences;
	/// Normal contract assembly items.
	std::optional<evmasm::AssemblyItems> assemblyItems;
	/// Normal contract runtime assembly items.
	std::optional<evmasm::AssemblyItems> runtimeAssemblyItems;
	/// Contract Metadata matching the pipeline selected using the viaIR setting.
	std::string metadata;
	/// CBOR-encoded metadata matching the pipeline selected using the viaIR
	/// setting.
	bytes cborMetadata;
	/// The contract ABI as a JSON object.
	Json contractABI;
	/// JSON object with the three members ``methods``, ``events``, ``errors``.
	/// Each is a map, mapping identifiers (hashes) to function names.
	Json interfaceSymbols;
	/// Event signatures
	std::vector<AnnotatedEventSignature> eventSignatures;
};

using SourceUnits = std::map<std::string, std::vector<CompiledContract>>;

/**
 * Output generated by the compiler. Provides convenient access method to the
 * internal data.
 */
class CompilerOutput
{
public:
	CompilerOutput(
		SourceUnits _sourceUnits,
		bool _success,
		langutil::ErrorList _errors,
		std::string _errorInformation
	):
		m_sourceUnits(_sourceUnits),
		m_success(_success),
		m_errors(_errors),
		m_errorInformation(_errorInformation)
	{} 

	/// @returns the compiled contract, if any was found.
	/// @param _sourceName find contracts for specific source name, if set.
	/// Find contracts for the empty source name.
	/// @param _contractName find a specific contract, if set. Take the last
	/// contract otherwise.
	std::optional<CompiledContract> contract(
		std::optional<std::string> _sourceName = std::nullopt,
		std::optional<std::string> _contractName = std::nullopt
	) const;

	/// @returns the annotated event sig for the hash given, if any.
	/// @param hash
	std::optional<AnnotatedEventSignature> matchEvent(
		util::h256 const& _hash
	) const;

	/// @returns true if no errors occurred during compilation.
	bool success() const;

	/// @returns the first error that matches the type specified, or none if no
	/// error for this type was found.
	/// @param _type the error type to look for.
	std::optional<langutil::Error> findError(langutil::Error::Type _type) const;

	/// @returns a formatted output of all errors that occured during
	/// compilation.
	std::string errorInformation() const;

private:
	/// All compiled contracts, indexed by source name.
	SourceUnits m_sourceUnits;
	/// If compilation was successful.
	bool m_success;
	/// All errors, if any.
	langutil::ErrorList m_errors;
	/// Formatted error information.
	std::string m_errorInformation;
};

}