// test various masks, some generated by the compiler internally

contract MaskTests {
    struct FitsInU256 {
        uint8 oneByte;
        uint96 bigNightySixer;
        uint64 sixtyFourMiddle;
        uint16 sixteener;
        uint72 seventyTwo;
    }

    FitsInU256 first;

    constructor() {
        first = FitsInU256(0x98, 0x010203040506070809a1b2c3, 0xdeadcafefeedbead, 0x1234, 0x102030405060708090);
    }

    // the compiler generates masks for these functions
    function firstOneByte() external view returns (uint8) {
        return first.oneByte;
    }

    function firstBigNightySixer() external view returns (uint96) {
        return first.bigNightySixer;
    }

    function firstSixtyFourMiddle() external view returns (uint64) {
        return first.sixtyFourMiddle;
    }

    function firstSixteener() external view returns (uint16) {
        return first.sixteener;
    }

    function firstSeventyTwo() external view returns (uint72) {
        return first.seventyTwo;
    }

    function setMiddleSixtyFour(uint64 x) external returns (uint96) {
        first.sixtyFourMiddle = x;
        return first.bigNightySixer + first.sixtyFourMiddle + first.sixteener;
    }

    // hand coded masks
    function add55(uint x) external pure returns (uint) {
        return x + ((uint(1) << 55) - 1);
    }

    function add155(uint x) external pure returns (uint) {
        return x + ((uint(1) << 155) - 1);
    }

    function add55shift(uint x) external pure returns (uint) {
        return x + (((uint(1) << 55) - 1) << 67);
    }

    function add155shift(uint x) external pure returns (uint) {
        return x + (((uint(1) << 155) - 1) << 67);
    }
}
// ====
// EVMVersion: =current
// ----
// firstOneByte() -> 0x98
// firstBigNightySixer() -> 0x010203040506070809a1b2c3
// firstSixtyFourMiddle() -> 0xdeadcafefeedbead
// firstSixteener() -> 0x1234
// firstSeventyTwo() -> 0x102030405060708090
// add55(uint256): 1 -> 0x80000000000000
// add55(uint256): 2 -> 0x80000000000001
// add55(uint256): 0x1000000000000000 -> 0x107fffffffffffff
// add155(uint256): 1 -> 0x800000000000000000000000000000000000000
// add55shift(uint256): 1 -> 0x3fffffffffffff80000000000000001
// add55shift(uint256): 0x80000000000000000 -> 0x4000000000000000000000000000000
// add155shift(uint256): 1 -> 0x3ffffffffffffffffffffffffffffffffffffff80000000000000001
// add155shift(uint256): 0x80000000000000000 -> 0x40000000000000000000000000000000000000000000000000000000
// setMiddleSixtyFour(uint64): 0 -> 0x010203040506070809a1c4f7
// setMiddleSixtyFour(uint64): 0xffffffffffffffff -> 0x010203050506070809a1c4f6
